version: '3.3'

services:
  backend:
    env_file:
    - .env
    image: api-backend-trabalho-sd-image
    build:
      context: ${BACKEND_API_NODE}
      dockerfile: docker/Dockerfile
    depends_on:
    - database

  gateway:
    env_file:
    - .env
    image: api-gateway-trabalho-sd-image
    build:
      context: ${GATEWAY}
      dockerfile: docker/Dockerfile

  database:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=golangDB
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=abc123
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    ports:
      - '27017-27019:27017-27019'