version: '3.3'

services:
  backend:
    image: api-backend-trabalho-sd-image
    build:
      context: ./backend
      dockerfile: docker/Dockerfile

  gateway:
    image: api-gateway-trabalho-sd-image
    build:
      context: ./gateway
      dockerfile: docker/Dockerfile