apiVersion: apps/v1
kind: Deployment
metadata:
    name: k8s-api-gateway-trabalho-sd
    labels:
        app: k8s-api-gateway-trabalho-sd
spec:
    replicas: 2
    selector:
        matchLabels:
            app: k8s-api-gateway-trabalho-sd
    template:
        metadata:
            labels:
                app: k8s-api-gateway-trabalho-sd
        spec:
            containers:
            - image: api-gateway-trabalho-sd-image
              imagePullPolicy: IfNotPresent
              name: k8s-api-gateway-trabalho-sd
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8009
                periodSeconds: 10
                failureThreshold: 3
                initialDelaySeconds: 20
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8009
                periodSeconds: 10
                failureThreshold: 5
                initialDelaySeconds: 3
              resources:
                requests:
                  memory: "10Mi"
                  cpu: "1m"
                limits:
                  memory: "20Mi"
                  cpu: "2m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-api-gateway-trabalho-sd-ingress
spec:
  rules:
    - host: api-gateway-trabalho-sd.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-api-gateway-trabalho-sd-service
                port:
                  number: 8009          
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api-gateway-trabalho-sd-service
  labels:
    app: k8s-api-gateway-trabalho-sd-service
spec:
  ports:
  - nodePort: 30010
    port: 80
    protocol: TCP
    targetPort: 8009
  selector:
    app: k8s-api-gateway-trabalho-sd
  type: NodePort
---
# AutoScaler do tipo Horizontal
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-api-gateway-trabalho-sd-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-api-gateway-trabalho-sd
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50