apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-trabalho-sd-api
  labels:
    app: k8s-trabalho-sd-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-trabalho-sd-api
  template:
    metadata:
      labels:
        app: k8s-trabalho-sd-api
    spec:
      containers:
      - name: k8s-trabalho-sd-api
        image: parmavictu/trabalho-sd-api:latest
        envFrom:
          - configMapRef:
              name: app-configmap
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: api-go-trabalho-sd-service
spec:
  selector:
    app: k8s-trabalho-sd-api
  type: ClusterIP
  ports:
  - name: http
    port: 5000
---
# AutoScaler do tipo Horizontal
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-go-trabalho-sd-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-trabalho-sd-api
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50