version: "3"
services:
  database:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=golangDB
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=abc123
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    ports:
      - '27017-27019:27017-27019'