{
 "title": "Kubernetes cluster monitoring (via Prometheus)",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\".*\", node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"default\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"minikube\", namespace=\"$namespace\", pod=~\"k8s-.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{instance=\"minikube\", namespace=\"$namespace\", pod=~\"k8s-.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All processes network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  }
 ]
}